version: '3.8'

services:
  db:
    image: postgres:17
    container_name: quotes-postgres
    env_file:
      - ../.env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
